### ISSUE TITLE
Malformed UTF-8 data when trying to download from cocomanhua

### ISSUE THREAD

**Issue by Lirikana** [Amd794/kanleying#4]
![image](https://user-images.githubusercontent.com/39252621/107156122-6a7ceb00-694a-11eb-9d8d-7c5b33840fdb.png)

**Comment by cmdragon** [comment]
run " npm i -D"

**Comment by Lirikana** [comment]
Failed again after trying. One package missing repository field
![image](https://user-images.githubusercontent.com/39252621/107375440-bf3d7480-6ab6-11eb-92c7-3eeb1a5934f0.png)
