### ISSUE TITLE
m.happymh.com timeout 

### ISSUE THREAD

**Issue by nakamiv** [Amd794/kanleying#5]
嗨皮漫画输入网址后直接连接超时3次退出。这个网站是用不了了吗？

**Comment by cmdragon** [comment]
挂上代理还可以用。 你可以尝试在浏览器打开链接，可以打开就可以下载。

**Comment by nakamiv** [comment]
> 挂上代理还可以用。 你可以尝试在浏览器打开链接，可以打开就可以下载。

可是我是海外的服务器，根本不用开代理就可以看这个网站....我用浏览器开chrome能正常打开，ie会遇到cloudflare验证，用这个工具是遇到这个验证所以超时了？

**Comment by cmdragon** [comment]
This website is using a security service to protect itself from online attacks.可能被拒绝访问了 Access denied。如果你自己有多个代理，可以尝试把proxy设置上。
